name: Build Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ksu:
        description: 'Enable KernelSU build'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies and Ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs ccache libssl-dev flex bison curl unzip
          echo "CCACHE_DIR: $HOME/.cache/ccache_mikernel"
          export CCACHE_DIR="$HOME/.cache/ccache_mikernel" 
          export CC="ccache gcc"
          export CXX="ccache g++"
          export PATH="/usr/lib/ccache:$PATH"

      # Шаг 1: Скачиваем и распаковываем тулчейн (Proton Clang)
      - name: Download Toolchain
        run: |
          mkdir proton-clang
          cd proton-clang
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
          unzip 20210522.zip
          mv proton-clang-20210522/* .
          cd ..
          
      # Шаг 2: Настраиваем переменные окружения, как в вашем скрипте
      - name: Set up Environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_COMPILER_STRING=clang" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=GitHub-Actions" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=github" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "PATH=$PATH:$PWD/proton-clang/bin" >> $GITHUB_ENV

      # Шаг 3: Клонируем AnyKernel3
      - name: Clone AnyKernel3
        run: git clone https://github.com/liyafe1997/AnyKernel3 -b kona --single-branch --depth=1 anykernel

      # Шаг 4: Применяем патчи KernelSU, если нужно
      - name: Apply KernelSU Patch
        run: |
          curl -LSs "https://github.com/liyafe1997/SukiSU-Ultra/raw/4ff14cf0051d04209c4abd5027d99d8e7780ef5b/kernel/setup.sh" | bash -s f4863b20cc8dc0f8cc67418980f022e43014b598
        if: ${{ github.event.inputs.ksu }}

      # Шаг 5: Вносим правки в Device Tree
      - name: Patch Device Tree
        run: |
          dts_source=arch/arm64/boot/dts/vendor/qcom
          sed -i 's/<154>/<1537>/g' ${dts_source}/dsi-panel-j1s*
          sed -i 's/<154>/<1537>/g' ${dts_source}/dsi-panel-j2*
          sed -i 's/<155>/<1544>/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
          sed -i 's/<155>/<1545>/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
          sed -i 's/<155>/<1546>/g' ${dts_source}/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
          sed -i 's/<155>/<1546>/g' ${dts_source}/dsi-panel-l11r-38-08-0a-dsc-cmd.dtsi
          sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
          sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
          sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
          sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-l11r-38-08-0a-dsc-cmd.dtsi
          sed -i 's/<71>/<710>/g' ${dts_source}/dsi-panel-j1s*
          sed -i 's/<71>/<710>/g' ${dts_source}/dsi-panel-j2*
          sed -i 's/\/\/ mi,mdss-dsi-pan-enable-smart-fps/mi,mdss-dsi-pan-enable-smart-fps/g' ${dts_source}/dsi-panel*
          sed -i 's/\/\/ mi,mdss-dsi-smart-fps-max_framerate/mi,mdss-dsi-smart-fps-max_framerate/g' ${dts_source}/dsi-panel*
          sed -i 's/\/\/ qcom,mdss-dsi-pan-enable-smart-fps/qcom,mdss-dsi-pan-enable-smart-fps/g' ${dts_source}/dsi-panel*
          sed -i 's/qcom,mdss-dsi-qsync-min-refresh-rate/\/\/qcom,mdss-dsi-qsync-min-refresh-rate/g' ${dts_source}/dsi-panel*
          sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-36-02-0c-dsc-video.dtsi
          sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-37-02-0a-dsc-video.dtsi
          sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-37-02-0b-dsc-video.dtsi
          sed -i 's/144 120 90 60/144 120 90 60 50 48 30/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 03 51 03 FF/39 00 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j9-38-0a-0a-fhd-video.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 03 51 0D FF/39 00 00 00 00 00 03 51 0D FF/g' ${dts_source}/dsi-panel-j2-p2-1-38-0c-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-mp-dsc-cmd.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2-mp-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2-p2-1-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2s-mp-42-02-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 00 00/39 01 00 00 00 00 03 51 00 00/g' ${dts_source}/dsi-panel-j2-38-0c-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 00 00/39 01 00 00 00 00 03 51 00 00/g' ${dts_source}/dsi-panel-j2-38-0c-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 03 FF/39 01 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 03 FF/39 01 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j9-38-0a-0a-fhd-video.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j1u-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j2-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j2-p1-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j1u-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j2-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j2-p1-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-mp-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2-mp-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2-p2-1-42-02-0b-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2s-mp-42-02-0a-dsc-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 01 00 03 51 03 FF/39 01 00 00 01 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
          sed -i 's/\/\/39 01 00 00 11 00 03 51 03 FF/39 01 00 00 11 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j2-p2-1-38-0c-0a-dsc-cmd.dtsi

      # Шаг 6: Настраиваем defconfig и дополнительные опции
      - name: Set Defconfig and build
        run: |
          make clean O=out ARCH=arm64 SUBARCH=arm64 CC=clang HOSTCC=gcc CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          make O=out lmi_defconfig ARCH=arm64 SUBARCH=arm64 CC=clang HOSTCC=gcc CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

          # Настройка конфига для KSU
          if [ "${{ github.event.inputs.ksu }}" == "true" ]; then
            scripts/config --file out/.config \
              -e KSU \
              -e KSU_MANUAL_HOOK \
              -e KSU_SUSFS_HAS_MAGIC_MOUNT \
              -d KSU_SUSFS_SUS_PATH \
              -e KSU_SUSFS_SUS_MOUNT \
              -e KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT \
              -e KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT \
              -e KSU_SUSFS_SUS_KSTAT \
              -d KSU_SUSFS_SUS_OVERLAYFS \
              -e KSU_SUSFS_TRY_UMOUNT \
              -e KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT \
              -e KSU_SUSFS_SPOOF_UNAME \
              -e KSU_SUSFS_ENABLE_LOG \
              -e KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS \
              -e KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG \
              -d KSU_SUSFS_OPEN_REDIRECT \
              -d KSU_SUSFS_SUS_SU \
              -e KPM
          else
            scripts/config --file out/.config -d KSU
          fi

          # Настройка других опций конфига
          scripts/config --file out/.config \
            --set-str STATIC_USERMODEHELPER_PATH /system/bin/micd \
            -e PERF_CRITICAL_RT_TASK \
            -e SF_BINDER \
            -e OVERLAY_FS \
            -d DEBUG_FS \
            -e MIGT \
            -e MIGT_ENERGY_MODEL \
            -e MIHW \
            -e PACKAGE_RUNTIME_INFO \
            -e BINDER_OPT \
            -e KPERFEVENTS \
            -e MILLET \
            -e PERF_HUMANTASK \
            -d LTO_CLANG \
            -d LOCALVERSION_AUTO \
            -e SF_BINDER \
            -e XIAOMI_MIUI \
            -d MI_MEMORY_SYSFS \
            -e TASK_DELAY_ACCT \
            -e MIUI_ZRAM_MEMORY_TRACKING \
            -d CONFIG_MODULE_SIG_SHA512 \
            -d CONFIG_MODULE_SIG_HASH \
            -e MI_FRAGMENTION \
            -e PERF_HELPER \
            -e BOOTUP_RECLAIM \
            -e MI_RECLAIM \
            -e RTMM

          # Запускаем сборку
          make -j$(nproc) O=out ARCH=arm64 SUBARCH=arm64 CC=clang HOSTCC=gcc CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

      # Шаг 7: СОЗДАНИЕ DTB-файла**
      - name: Create DTB
        run: |
          find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + >out/arch/arm64/boot/dtb

      # Шаг 8: Патчим для SukiSU KPM, если нужно
      - name: Patch for SukiSU KPM
        run: |
          cd out/arch/arm64/boot/
          wget https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm Image
          mv oImage Image
          cd -
        if: ${{ github.event.inputs.ksu }}

      # Шаг 9: Копируем файлы в AnyKernel3
      - name: Copy Files to AnyKernel3
        run: |
          mkdir -p anykernel/kernels/
          cp out/arch/arm64/boot/Image anykernel/kernels/
          cp out/arch/arm64/boot/dtb anykernel/kernels/

      # Шаг 10: Создаем ZIP-установщик
      - name: Create Flashable Zip
        run: |
          KSU_ZIP_STR="NoKernelSU"
          if [ "${{ github.event.inputs.ksu }}" == "true" ]; then
            KSU_ZIP_STR="SukiSU-SUSFS"
          fi
          ZIP_FILENAME="Kernel_MIUI_lmi_${KSU_ZIP_STR}_$(date +'%Y%m%d_%H%M%S')_anykernel3.zip"
          cd anykernel
          zip -r9 ../$ZIP_FILENAME ./*

      # Шаг 11: Загружаем готовый ZIP
      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: Flashable-Zip
          path: "*.zip"
